/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "qbdaqpkdtcukljganman"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFiZGFxcGtkdGN1a2xqZ2FubWFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM2NTAwNTQsImV4cCI6MjA3OTIyNjA1NH0.e9-FoCphiqIoovOmfDTZA-ibXPL7jcGhC4Kg_Xkts8I"